---

hostname: frawan01
domain_name: networks.dell.com

celoopback:
  address: 172.1.0.111
  mask: 255.255.255.255


interfaces:


  0/1.110:
    alias: connection pe-dublin
    bandwidth: 100000
    vlan: 100
    address: 192.168.110.2
    mask: 255.255.255.252


bgp:
  asn: 65122
  neighbor:
    - {address: 192.168.110.1, remote_as: 1}
